version: '3'

services:

  keycloak:
    platform: linux/amd64
    image: quay.io/keycloak/keycloak:${KC_VERSION:-18.0.2}
    entrypoint: [ ]
    command: [ "bash", "-c", "DEBUG=false /opt/keycloak/bin/kc.sh import --dir /opt/keycloak/data/import && /opt/keycloak/bin/kc.sh start --import-realm" ]
    # command: [ "/opt/keycloak/bin/kc.sh", "start" , "--import-realm" ]
    volumes:
      - ./realm-config/local:/opt/keycloak/data/import
      - ./realm-config/realm-export/local:/opt/keycloak/export
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin1234
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      DEBUG: 'true'
      DEBUG_SUSPEND: 'y'
      DEBUG_PORT: '*:5005'
    ports:
      - 8080:8080
      - 5005:5005

